services:
  aspire-dashboard:
    container_name: aspire-dashboard
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888

  relma.api-service:
    container_name: relma.api-service
    image: ${DOCKER_REGISTRY-}relma.apiservice
    build:
      context: .
      dockerfile: src/RelMa.ApiService/Dockerfile
    ports:
      - 8081:8080
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
    volumes:
      - ./.backup/api/statics:/app/statics
    depends_on:
      - aspire-dashboard

  relma.web-app:
    container_name: relma.web-app
    image: ${DOCKER_REGISTRY-}web
    build:
      context: ./src/RelMa.Web
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - relma.api-service
