// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RelMa.Infrastructure.Database;

#nullable disable

namespace RelMa.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PartsAndItems", b =>
                {
                    b.Property<string>("PartId")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("part_id");

                    b.Property<string>("ItemId")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("item_id");

                    b.HasKey("PartId", "ItemId")
                        .HasName("pk_parts_and_items");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_parts_and_items_item_id");

                    b.ToTable("parts_and_items", "public");
                });

            modelBuilder.Entity("RelMa.Domain.Assets.AssetEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("Area")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("area");

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("barcode");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("location_id");

                    b.Property<string>("ManufacturerId")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("manufacturer_id");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("serial_number");

                    b.Property<string>("TenantId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_assets");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_assets_location_id");

                    b.HasIndex("ManufacturerId")
                        .HasDatabaseName("ix_assets_manufacturer_id");

                    b.ToTable("assets", "public");
                });

            modelBuilder.Entity("RelMa.Domain.Checklists.ChecklistEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("task_id");

                    b.Property<string>("TenantId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("WorkOrderId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("work_order_id");

                    b.HasKey("Id")
                        .HasName("pk_checklist_entity");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_checklist_entity_task_id");

                    b.HasIndex("WorkOrderId")
                        .HasDatabaseName("ix_checklist_entity_work_order_id");

                    b.ToTable("checklist_entity", "public");
                });

            modelBuilder.Entity("RelMa.Domain.Files.FileEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Ext")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<long>("Size")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("size");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("source");

                    b.Property<string>("TenantId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_file_entity");

                    b.ToTable("file_entity", "public");
                });

            modelBuilder.Entity("RelMa.Domain.Items.ItemEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LocationId")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("location_id");

                    b.Property<string>("MaterialId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("material_id");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("StorageId")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("storage_id");

                    b.Property<string>("TenantId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_items_location_id");

                    b.HasIndex("MaterialId")
                        .HasDatabaseName("ix_items_material_id");

                    b.HasIndex("StorageId")
                        .HasDatabaseName("ix_items_storage_id");

                    b.ToTable("items", "public");
                });

            modelBuilder.Entity("RelMa.Domain.Locations.LocationEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("ParentId")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("parent_id");

                    b.Property<string>("TenantId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_locations_parent_id");

                    b.ToTable("locations", "public");
                });

            modelBuilder.Entity("RelMa.Domain.Maintenances.MaintenanceEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("asset_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_maintenance_entity");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_maintenance_entity_asset_id");

                    b.ToTable("maintenance_entity", "public");
                });

            modelBuilder.Entity("RelMa.Domain.Manufacturers.ManufacturerEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("TenantId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_manufacturer_entity");

                    b.ToTable("manufacturer_entity", "public");
                });

            modelBuilder.Entity("RelMa.Domain.Materials.MaterialEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<int>("AllocatedQty")
                        .HasColumnType("integer")
                        .HasColumnName("allocated_qty");

                    b.Property<int>("AvailableQty")
                        .HasColumnType("integer")
                        .HasColumnName("available_qty");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<int>("IncomingQty")
                        .HasColumnType("integer")
                        .HasColumnName("incoming_qty");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("MinQty")
                        .HasColumnType("integer")
                        .HasColumnName("min_qty");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_materials");

                    b.ToTable("materials", "public");
                });

            modelBuilder.Entity("RelMa.Domain.Parts.PartEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("image");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("part_number");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("quantity");

                    b.Property<string>("TenantId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("WorkOrderEntityId")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("work_order_entity_id");

                    b.HasKey("Id")
                        .HasName("pk_part_entity");

                    b.HasIndex("WorkOrderEntityId")
                        .HasDatabaseName("ix_part_entity_work_order_entity_id");

                    b.ToTable("part_entity", "public");
                });

            modelBuilder.Entity("RelMa.Domain.Requests.RequestEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("asset_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_requests");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_requests_asset_id");

                    b.ToTable("requests", "public");
                });

            modelBuilder.Entity("RelMa.Domain.Sets.SetEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("TenantId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_set_entity");

                    b.ToTable("set_entity", "public");
                });

            modelBuilder.Entity("RelMa.Domain.Storages.StorageEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LocationId")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("location_id");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_storages");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_storages_location_id");

                    b.ToTable("storages", "public");
                });

            modelBuilder.Entity("RelMa.Domain.Tasks.TaskEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("asset_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("TenantId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<JsonDocument>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value");

                    b.Property<string>("WorkOrderEntityId")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("work_order_entity_id");

                    b.HasKey("Id")
                        .HasName("pk_task_entity");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_task_entity_asset_id");

                    b.HasIndex("WorkOrderEntityId")
                        .HasDatabaseName("ix_task_entity_work_order_entity_id");

                    b.ToTable("task_entity", "public");
                });

            modelBuilder.Entity("RelMa.Domain.Teams.TeamEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LeaderId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("leader_id");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("TenantId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_team_entity");

                    b.HasIndex("LeaderId")
                        .HasDatabaseName("ix_team_entity_leader_id");

                    b.ToTable("team_entity", "public");
                });

            modelBuilder.Entity("RelMa.Domain.Users.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Company")
                        .HasColumnType("text")
                        .HasColumnName("company");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("TenantId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_user_entity");

                    b.ToTable("user_entity", "public");
                });

            modelBuilder.Entity("RelMa.Domain.WorkOrders.WorkOrderEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("MaintenanceId")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("maintenance_id");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("RequestId")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("request_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_work_orders");

                    b.HasIndex("MaintenanceId")
                        .IsUnique()
                        .HasDatabaseName("ix_work_orders_maintenance_id");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_work_orders_request_id");

                    b.ToTable("work_orders", "public");
                });

            modelBuilder.Entity("SetsAndParts", b =>
                {
                    b.Property<string>("PartId")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("part_id");

                    b.Property<string>("SetId")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("set_id");

                    b.HasKey("PartId", "SetId")
                        .HasName("pk_sets_and_parts");

                    b.HasIndex("SetId")
                        .HasDatabaseName("ix_sets_and_parts_set_id");

                    b.ToTable("sets_and_parts", "public");
                });

            modelBuilder.Entity("TeamsAndMembers", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("TeamId")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("team_id");

                    b.HasKey("UserId", "TeamId")
                        .HasName("pk_teams_and_members");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_teams_and_members_team_id");

                    b.ToTable("teams_and_members", "public");
                });

            modelBuilder.Entity("PartsAndItems", b =>
                {
                    b.HasOne("RelMa.Domain.Items.ItemEntity", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parts_and_items_items_item_id");

                    b.HasOne("RelMa.Domain.Parts.PartEntity", null)
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parts_and_items_part_entity_part_id");
                });

            modelBuilder.Entity("RelMa.Domain.Assets.AssetEntity", b =>
                {
                    b.HasOne("RelMa.Domain.Locations.LocationEntity", "Location")
                        .WithMany("Assets")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assets_locations_location_id");

                    b.HasOne("RelMa.Domain.Manufacturers.ManufacturerEntity", "Manufacturer")
                        .WithMany("Assets")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_assets_manufacturer_entity_manufacturer_id");

                    b.Navigation("Location");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("RelMa.Domain.Checklists.ChecklistEntity", b =>
                {
                    b.HasOne("RelMa.Domain.Tasks.TaskEntity", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_checklist_entity_task_entity_task_id");

                    b.HasOne("RelMa.Domain.WorkOrders.WorkOrderEntity", "WorkOrder")
                        .WithMany("Checklists")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_checklist_entity_work_orders_work_order_id");

                    b.Navigation("Task");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("RelMa.Domain.Items.ItemEntity", b =>
                {
                    b.HasOne("RelMa.Domain.Locations.LocationEntity", "Location")
                        .WithMany("Items")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_items_locations_location_id");

                    b.HasOne("RelMa.Domain.Materials.MaterialEntity", "Material")
                        .WithMany("Items")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_items_materials_material_id");

                    b.HasOne("RelMa.Domain.Storages.StorageEntity", "Storage")
                        .WithMany("Items")
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_items_storages_storage_id");

                    b.Navigation("Location");

                    b.Navigation("Material");

                    b.Navigation("Storage");
                });

            modelBuilder.Entity("RelMa.Domain.Locations.LocationEntity", b =>
                {
                    b.HasOne("RelMa.Domain.Locations.LocationEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_locations_locations_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("RelMa.Domain.Maintenances.MaintenanceEntity", b =>
                {
                    b.HasOne("RelMa.Domain.Assets.AssetEntity", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_maintenance_entity_assets_asset_id");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("RelMa.Domain.Parts.PartEntity", b =>
                {
                    b.HasOne("RelMa.Domain.WorkOrders.WorkOrderEntity", null)
                        .WithMany("Parts")
                        .HasForeignKey("WorkOrderEntityId")
                        .HasConstraintName("fk_part_entity_work_orders_work_order_entity_id");
                });

            modelBuilder.Entity("RelMa.Domain.Requests.RequestEntity", b =>
                {
                    b.HasOne("RelMa.Domain.Assets.AssetEntity", "Asset")
                        .WithMany("Requests")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_requests_assets_asset_id");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("RelMa.Domain.Storages.StorageEntity", b =>
                {
                    b.HasOne("RelMa.Domain.Locations.LocationEntity", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .HasConstraintName("fk_storages_locations_location_id");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("RelMa.Domain.Tasks.TaskEntity", b =>
                {
                    b.HasOne("RelMa.Domain.Assets.AssetEntity", "Asset")
                        .WithMany("Tasks")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_entity_assets_asset_id");

                    b.HasOne("RelMa.Domain.WorkOrders.WorkOrderEntity", null)
                        .WithMany("Tasks")
                        .HasForeignKey("WorkOrderEntityId")
                        .HasConstraintName("fk_task_entity_work_orders_work_order_entity_id");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("RelMa.Domain.Teams.TeamEntity", b =>
                {
                    b.HasOne("RelMa.Domain.Users.UserEntity", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_entity_user_entity_leader_id");

                    b.Navigation("Leader");
                });

            modelBuilder.Entity("RelMa.Domain.WorkOrders.WorkOrderEntity", b =>
                {
                    b.HasOne("RelMa.Domain.Maintenances.MaintenanceEntity", "Maintenance")
                        .WithOne("WorkOrder")
                        .HasForeignKey("RelMa.Domain.WorkOrders.WorkOrderEntity", "MaintenanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_work_orders_maintenance_entity_maintenance_id");

                    b.HasOne("RelMa.Domain.Requests.RequestEntity", "Request")
                        .WithOne("WorkOrder")
                        .HasForeignKey("RelMa.Domain.WorkOrders.WorkOrderEntity", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_work_orders_requests_request_id");

                    b.Navigation("Maintenance");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("SetsAndParts", b =>
                {
                    b.HasOne("RelMa.Domain.Parts.PartEntity", null)
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sets_and_parts_part_entity_part_id");

                    b.HasOne("RelMa.Domain.Sets.SetEntity", null)
                        .WithMany()
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sets_and_parts_set_entity_set_id");
                });

            modelBuilder.Entity("TeamsAndMembers", b =>
                {
                    b.HasOne("RelMa.Domain.Teams.TeamEntity", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teams_and_members_team_entity_team_id");

                    b.HasOne("RelMa.Domain.Users.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teams_and_members_user_entity_user_id");
                });

            modelBuilder.Entity("RelMa.Domain.Assets.AssetEntity", b =>
                {
                    b.Navigation("Requests");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("RelMa.Domain.Locations.LocationEntity", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Children");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("RelMa.Domain.Maintenances.MaintenanceEntity", b =>
                {
                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("RelMa.Domain.Manufacturers.ManufacturerEntity", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("RelMa.Domain.Materials.MaterialEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("RelMa.Domain.Requests.RequestEntity", b =>
                {
                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("RelMa.Domain.Storages.StorageEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("RelMa.Domain.WorkOrders.WorkOrderEntity", b =>
                {
                    b.Navigation("Checklists");

                    b.Navigation("Parts");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
